function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy as a
%       percentage. In the app, the Models pane displays this overall
%       accuracy score for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 22-Apr-2023 22:29:42


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'MFCC1Mean', 'MFCC2Mean', 'MFCC3Mean', 'MFCC4Mean', 'MFCC5Mean', 'MFCC6Mean', 'MFCC7Mean', 'MFCC8Mean', 'MFCC9Mean', 'MFCC10Mean', 'MFCC11Mean', 'MFCC12Mean', 'MFCC13Mean', 'MFCC1Var', 'MFCC2Var', 'MFCC3Var', 'MFCC4Var', 'MFCC5Var', 'MFCC6Var', 'MFCC7Var', 'MFCC8Var', 'MFCC9Var', 'MFCC10Var', 'MFCC11Var', 'MFCC12Var', 'MFCC13Var', 'MFCC1Max', 'MFCC2Max', 'MFCC3Max', 'MFCC4Max', 'MFCC5Max', 'MFCC6Max', 'MFCC7Max', 'MFCC8Max', 'MFCC9Max', 'MFCC10Max', 'MFCC11Max', 'MFCC12Max', 'MFCC13Max', 'MFCC1Min', 'MFCC2Min', 'MFCC3Min', 'MFCC4Min', 'MFCC5Min', 'MFCC6Min', 'MFCC7Min', 'MFCC8Min', 'MFCC9Min', 'MFCC10Min', 'MFCC11Min', 'MFCC12Min', 'MFCC13Min'};
predictors = inputTable(:, predictorNames);
response = inputTable.Genre;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateSVM(...
    'KernelFunction', 'gaussian', ...
    'PolynomialOrder', [], ...
    'KernelScale', 6.356296326879919, ...
    'BoxConstraint', 554.2660689941667, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsall', ...
    'ClassNames', categorical({'Blues'; 'Classical'; 'Country'; 'Disco'; 'Hiphop'; 'Jazz'; 'Metal'; 'Pop'; 'Reggae'; 'Rock'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'MFCC10Max', 'MFCC10Mean', 'MFCC10Min', 'MFCC10Var', 'MFCC11Max', 'MFCC11Mean', 'MFCC11Min', 'MFCC11Var', 'MFCC12Max', 'MFCC12Mean', 'MFCC12Min', 'MFCC12Var', 'MFCC13Max', 'MFCC13Mean', 'MFCC13Min', 'MFCC13Var', 'MFCC1Max', 'MFCC1Mean', 'MFCC1Min', 'MFCC1Var', 'MFCC2Max', 'MFCC2Mean', 'MFCC2Min', 'MFCC2Var', 'MFCC3Max', 'MFCC3Mean', 'MFCC3Min', 'MFCC3Var', 'MFCC4Max', 'MFCC4Mean', 'MFCC4Min', 'MFCC4Var', 'MFCC5Max', 'MFCC5Mean', 'MFCC5Min', 'MFCC5Var', 'MFCC6Max', 'MFCC6Mean', 'MFCC6Min', 'MFCC6Var', 'MFCC7Max', 'MFCC7Mean', 'MFCC7Min', 'MFCC7Var', 'MFCC8Max', 'MFCC8Mean', 'MFCC8Min', 'MFCC8Var', 'MFCC9Max', 'MFCC9Mean', 'MFCC9Min', 'MFCC9Var'};
trainedClassifier.ClassificationSVM = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2021b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'MFCC1Mean', 'MFCC2Mean', 'MFCC3Mean', 'MFCC4Mean', 'MFCC5Mean', 'MFCC6Mean', 'MFCC7Mean', 'MFCC8Mean', 'MFCC9Mean', 'MFCC10Mean', 'MFCC11Mean', 'MFCC12Mean', 'MFCC13Mean', 'MFCC1Var', 'MFCC2Var', 'MFCC3Var', 'MFCC4Var', 'MFCC5Var', 'MFCC6Var', 'MFCC7Var', 'MFCC8Var', 'MFCC9Var', 'MFCC10Var', 'MFCC11Var', 'MFCC12Var', 'MFCC13Var', 'MFCC1Max', 'MFCC2Max', 'MFCC3Max', 'MFCC4Max', 'MFCC5Max', 'MFCC6Max', 'MFCC7Max', 'MFCC8Max', 'MFCC9Max', 'MFCC10Max', 'MFCC11Max', 'MFCC12Max', 'MFCC13Max', 'MFCC1Min', 'MFCC2Min', 'MFCC3Min', 'MFCC4Min', 'MFCC5Min', 'MFCC6Min', 'MFCC7Min', 'MFCC8Min', 'MFCC9Min', 'MFCC10Min', 'MFCC11Min', 'MFCC12Min', 'MFCC13Min'};
predictors = inputTable(:, predictorNames);
response = inputTable.Genre;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationSVM, 'KFold', 10);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
